const root=document.getElementById('stage'),surface=document.getElementById('surface');
const q=new URLSearchParams(location.search);let version=['a','b','c'].includes(q.get('v'))?q.get('v'):'a';let screen=q.get('screen')||'battle';let selected='flame_charger';let reduced=false;let noticeTimer;
const cards=Object.fromEntries(window.DW_CARDS.map(c=>[c.id,c]));
const directions={a:'A · 竞赛转播 / 横向信息节奏',b:'B · 彩印发行 / 包装与参数结构',c:'C · 未来教室 / 设备与模块层叠'};
const artClass={flame_recruit:'recruit',flame_imp:'imp',flame_charger:'charger',flame_guard:'guard',flame_leader:'recruit',sea_crab:'crab'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(id,big=false){let c=cards[id];return `<${big?'div':'button'} class="${big?'bigcard':'card'} ${id.startsWith('sea')?'sea':''}" ${big?'':`data-card="${id}" aria-label="查看${esc(c.name)}，惩罚${c.punish}，攻击${c.attack}，生命${c.health}"`}><div class="card-top"><span class="card-name">${esc(c.name)}</span><span class="pval">惩罚<b>${c.punish}</b></span></div><div class="art ${artClass[id]}" role="img" aria-label="${esc(c.name)}插画候选"></div><span class="serial">${id==='sea_crab'?'SEA':'FLAME'}</span><div class="stats"><span>攻<b>${c.attack}</b></span><span>生命<b>${c.health}</b></span><span class="type">随从</span></div>${big?`<div class="cardcopy">${esc(c.text||'无额外能力。')}</div>`:''}</${big?'div':'button'}>`}
function mast(label){return `<header class="mast"><div class="brand">统御战纪<small>DOMINION<br>WARS</small></div><span class="edition">${version==='b'?'幻想战争 · 卡牌系列':version==='c'?'STRATEGY / PLAY SYSTEM':'DUEL / STRATEGY CARD GAME'}</span><span class="section">${label}</span><button data-action="menu">菜单 ≡</button></header>`}
function zone(name,count,icon){return `<button class="zone" data-zone="${name}"><span class="zi">${icon}</span><span class="zn">${name}</span><b>${count}</b><span class="arrow">↗</span></button>`}
function battle(damage=false){return mast('对战')+`<div class="battle"><div class="playmat"><div class="playerbar"><span class="side">对手</span><span class="name">深海联盟</span><span class="state">统领未降临</span><span class="metric">牌库<b>47</b></span><span class="metric">墓地<b>3</b></span><span class="metric">循环<b>0</b></span></div><div class="enemy-hand"><label>对方手牌 · 5</label>${'<span class="back" aria-label="隐藏手牌"></span>'.repeat(5)}<span class="ambushmark">对方伏击 · 1 张盖牌</span></div><div class="row"><span class="row-label">对方战场</span>${card('sea_crab')}${card('sea_crab')}</div><div class="castle"><span class="castle-icon">▥</span><strong>王城</strong><div class="bar"></div><span class="number">75<small> / 75</small></span><span class="shared">双方共享<br>中立区域</span></div><div class="row own"><span class="row-label">己方战场</span>${card('flame_recruit')}${card('flame_imp')}</div><div class="own-strip"><strong>己方 · 烈焰帝国</strong><span>统领未降临</span><span>伏击 · 0</span><span>循环计数 · 0</span></div><div class="hand">${['flame_recruit','flame_imp','flame_charger','flame_charger','flame_recruit'].map(id=>card(id)).join('')}</div><div class="hand-caption"><span>手牌</span><b>05</b><span> / 点击读牌</span><span class="hint">卡牌信息来自项目数据</span></div></div><aside class="rail"><div class="turn"><span>当前回合<br>TURN</span><strong>04</strong></div><div class="phase">行动阶段</div><div class="turn-owner">当前操作方：己方</div><div class="pile-head"><span>己方区域</span><span>数量 / 查看</span></div>${zone('牌库',46,'▤')}${zone('墓地',4,'▱')}${zone('提交队列',0,'→')}${zone('云端',0,'↑')}<p class="quiet">队列与云端独立显示<br>展开后查看顺序与栈顶</p><div class="log"><h3>战报　↗</h3><p>进入行动阶段</p><small>当前没有待处理的响应</small></div><button class="end" data-action="end">结束回合 <span>→</span></button><div class="visual-state">按钮仅演示视觉反馈</div></aside></div>${damage?'<div class="damage-overlay"><div class="damage-label">伤害结算</div><div class="damage-number">−2</div><div class="damage-caption">铁甲蟹 · 生命 4 → 2　/　独立演出示例</div></div>':''}`}
function detail(){const c=cards[selected];return mast('卡牌详情')+`<div class="page"><div class="eyebrow">CARD INFORMATION / 卡牌资料</div><div class="detail-layout">${card(selected,true)}<article class="details"><h1>${esc(c.name)}</h1><div class="factionlabel"><span>${esc(c.faction)} / 随从</span><span>${esc(c.tags?.join(' · ')||'')}</span></div><div class="paramtable"><div class="param"><small>打印惩罚值</small><b>${c.punish}</b></div><div class="param"><small>攻击力</small><b>${c.attack}</b></div><div class="param"><small>生命值</small><b>${c.health}</b></div></div><div class="rules-title">卡牌能力</div><p class="rules">${esc(c.text||'无额外能力。')}</p>${c.keywords?.length?`<p><b>关键词</b>　${esc(c.keywords.join(' · '))}</p>`:''}<p class="explanation">惩罚值与攻血分栏呈现。对局中的有效值与可执行行动由引擎决定。</p><p class="explanation">本页使用项目卡牌文案；插画为风格候选，不是定稿角色设定。</p><button class="backbutton" data-screen="battle">← 返回战场</button></article></div></div>`}
function deck(){return mast('卡组构筑')+`<div class="page"><div class="eyebrow">COLLECTION / 幻想战争卡牌</div><div class="deck-layout"><div><div class="deck-head"><h1>烈焰帝国</h1><div class="filterset"><button class="active" data-filter="all">全部</button><button data-filter="recruit">士兵</button><button data-filter="charger">骑兵</button></div></div><div class="deck-grid">${['flame_recruit','flame_imp','flame_charger','flame_recruit','flame_charger','flame_imp','flame_recruit','flame_charger'].map(id=>card(id)).join('')}</div></div><aside class="deck-ledger"><h2>构筑清单</h2><div class="small">当前展示局部选牌流程<br>并非已验证的完整卡组</div><div class="ledger-count">05 <small>张已选示例卡</small></div><div class="ledger-item"><span>烈焰新兵</span><b>×2</b></div><div class="ledger-item"><span>火舌小鬼</span><b>×1</b></div><div class="ledger-item"><span>冲锋骑兵</span><b>×2</b></div><p class="small">统领：待选择<br>完整构筑合法性：未验证</p><button class="backbutton" data-action="save">保存草稿 →</button></aside></div></div>`}
function victory(){return mast('对局结算')+`<section class="result"><div class="eyebrow">RESULT / 独立结算画面样例</div><div class="victory-title">胜利</div><div class="reason">烈焰帝国 · 击破王城</div><div class="result-note">胜因展示样例 · 不代表前述对局已经结束</div><div class="result-meta"><div><b>王城</b><span>胜因对象</span></div><div><b>击破</b><span>结果状态</span></div><div><b>烈焰帝国</b><span>获胜方</span></div></div><div class="result-actions"><button data-screen="battle">再看战场 →</button><button data-screen="deck">返回卡组</button></div><div class="giant-mark">胜</div></section>`}
function render(){root.className=`theme-${version}${reduced?' reduced':''}`;surface.innerHTML=screen==='detail'?detail():screen==='deck'?deck():screen==='victory'?victory():battle(screen==='damage');document.getElementById('direction').textContent=directions[version];document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===version));document.querySelectorAll('#reviewbar [data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));history.replaceState(null,'',`?v=${version}&screen=${screen}`);fit()}
function fit(){let scale=Math.min(innerWidth/1440,(innerHeight-96)/900);scale=Math.max(.2,scale);root.style.transform=`scale(${scale})`;root.style.left=Math.max(0,(innerWidth-1440*scale)/2)+'px';document.getElementById('viewport').style.height=900*scale+'px'}
function notify(msg){const n=document.getElementById('notice');n.textContent=msg;n.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('show'),2600)}
function change(next){if(reduced){next();return}let w=document.getElementById('wipe');w.classList.remove('run');void w.offsetWidth;w.classList.add('run');setTimeout(next,220);setTimeout(()=>w.classList.remove('run'),510)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.v){change(()=>{version=b.dataset.v;render()});return}if(b.dataset.screen){change(()=>{screen=b.dataset.screen;render()});return}if(b.dataset.card){selected=b.dataset.card;change(()=>{screen='detail';render()});return}if(b.dataset.zone){let name=b.dataset.zone;surface.insertAdjacentHTML('beforeend',`<section class="drawer"><button data-close>关闭 ×</button><h2>己方 · ${name}</h2><div class="empty">${name==='云端'?'当前云端为空；存在卡牌时突出栈顶，不显示固定容量格。':name==='提交队列'?'当前提交队列为空；队列内容按实际顺序展开。':'此处展示区域展开的版式，未连接对局数据。'}</div></section>`);return}if(b.hasAttribute('data-close')){b.closest('.drawer').remove();return}if(b.dataset.filter){document.querySelectorAll('.filterset button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.deck-grid .card').forEach(x=>{x.style.display=b.dataset.filter==='all'||x.dataset.card.endsWith(b.dataset.filter)?'flex':'none'});return}if(b.dataset.action)notify('视觉样稿：此操作不更改对局或保存数据。')});
document.getElementById('motionToggle').onclick=()=>{reduced=!reduced;document.getElementById('motionToggle').setAttribute('aria-pressed',String(reduced));document.getElementById('motionToggle').textContent=reduced?'动态已减少':'减少动态';render()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){let d=document.querySelector('.drawer');if(d)d.remove();else if(screen==='detail'){screen='battle';render()}}});addEventListener('resize',fit);render();
