// Round two: concrete corrections from the three read-only reviewers.
const originalCard=card,originalBattle=battle,originalDetail=detail,originalRender=render;
artClass.sea_leader='crab';artClass.flame_punish_wrath='imp';
const quantities={flame_recruit:2,flame_imp:1,flame_charger:2};
card=function(id,big=false){const c=cards[id],type=c.type==='MINION'?'随从':c.type==='SPELL'?'咒文':c.type==='PUNISH'?'惩罚牌':c.type;let html=originalCard(id,big);const badges=[...(c.keywords||[]),...(c.text?.includes('登场')?['登场能力']:[])];if(c.type==='MINION'){html=html.replace('<div class="stats">',`<div class="abilities">${badges.length?esc(badges.join(' · ')):'基础随从'}</div><div class="stats">`)}else{html=html.replace(/<div class="stats">[\s\S]*?<\/div>/,`<div class="stats"><span class="type">${esc(type)}${c.leader?' · 统领':''}</span><span>无攻血</span></div>`)}if(big&&c.keywords?.length&&(!c.text||!c.text.includes(c.keywords[0]))){html=html.replace('无额外能力。',esc(c.keywords.join(' · ')))}return html.replaceAll('undefined','—').replaceAll('null','—')};
battle=function(damage=false){let html=originalBattle(damage);html=html.replace('<span class="state">统领未降临</span>','<span class="state">统领未降临</span><button class="public-summary" data-opponent>云端 0 · 队列 0 ↗</button>');html=html.replace('<span>伏击 · 0</span>','<button class="ambush-button" data-own-ambush>伏击 · 0 ↗</button>');html=html.replace('<span>己方区域</span><span>数量 / 查看</span>','<span class="owner-switch"><button class="active" data-owner="own">己方</button><button data-owner="enemy">对方</button></span><span>公共区域</span>');return html};
detail=function(){let html=originalDetail();const c=cards[selected];if(c.type!=='MINION'){html=html.replace(' / 随从',' / '+(c.type==='SPELL'?'咒文':'惩罚牌'));html=html.replace('<small>攻击力</small><b>null</b>','<small>攻击力</small><b>—</b>').replace('<small>生命值</small><b>null</b>','<small>生命值</small><b>—</b>').replaceAll('<b>undefined</b>','<b>—</b>');}if(c.punishCost!==undefined)html=html.replace('<div class="rules-title">',`<div class="punishcost">惩罚降临费用 <b>${c.punishCost}</b><span>仅在相应触发与条件满足时适用</span></div><div class="rules-title">`);if(selected==='sea_leader')html=html.replace('无额外能力。','统领 · 赋予生命');return html};
deck=function(){const sum=Object.values(quantities).reduce((a,b)=>a+b,0);return mast('卡组构筑')+`<div class="page"><div class="eyebrow">COLLECTION / 每种卡独立展示</div><div class="deck-layout"><div><div class="deck-head"><h1>烈焰帝国</h1><div class="filterset"><button class="active" data-filter="all">全部</button><button data-filter="recruit">士兵</button><button data-filter="charger">骑兵</button></div></div><div class="deck-grid unique-grid">${Object.keys(quantities).map(id=>`<div class="collection-item" data-kind="${id.split('_')[1]}">${card(id)}<div class="quantity-control"><button data-qty="${id}" data-delta="-1" aria-label="减少${cards[id].name}">−</button><span>已选 <b>${quantities[id]}</b></span><button data-qty="${id}" data-delta="1" aria-label="增加${cards[id].name}">＋</button></div><p>${esc(cards[id].text||'基础随从 · 无额外能力')}</p></div>`).join('')}</div><div class="collection-note"><b>选牌 → 查看能力 → 调整数量</b><span>此样稿展示三种卡的构筑操作，不代表完整收藏。</span></div></div><aside class="deck-ledger"><h2>构筑清单</h2><div class="small">局部选牌样例<br>每种卡的数量与左侧同步</div><div class="ledger-count">${String(sum).padStart(2,'0')} <small>张已选示例卡</small></div>${Object.keys(quantities).map(id=>`<div class="ledger-item"><span>${cards[id].name}</span><b>×${quantities[id]}</b></div>`).join('')}<p class="small">统领：待选择<br>完整构筑合法性：未验证</p><button class="backbutton" data-action="save">保存草稿 →</button></aside></div></div>`};
function showZones(){document.querySelector('.drawer')?.remove();surface.insertAdjacentHTML('beforeend',`<section class="drawer sample-zones"><button data-close>关闭 ×</button><div class="eyebrow">独立区域样例 · 非引擎局面</div><h2>己方公共区域</h2><p>使用真实卡名测试列表排版；<br>不表示这些卡当前具有上传能力。</p><h3>提交队列 <small>2 张</small></h3><ol class="ordered-cards"><li><b>队首</b><span>烈焰新兵</span><i>01</i></li><li><b>后续</b><span>火舌小鬼</span><i>02</i></li></ol><h3>云端 <small>2 张</small></h3><ol class="ordered-cards cloud-list"><li><b>栈顶</b><span>冲锋骑兵</span><i>↑</i></li><li><b>下层</b><span>烈焰新兵</span><i>↓</i></li></ol><p>只突出栈顶，不显示虚构容量格。<br>实际公开信息与可操作性由引擎提供。</p></section>`)}
render=function(){if(screen==='long'){selected='sea_leader';screen='detail'}if(screen==='cost'){selected='flame_punish_wrath';screen='detail'}originalRender();if(screen==='damage'){const target=document.querySelector('.row .card');target.classList.add('damage-target');const r=target.getBoundingClientRect(),s=root.getBoundingClientRect(),scale=s.width/1440;const num=document.querySelector('.damage-number');num.style.left=(r.left-s.left)/scale+74+'px';num.style.top=(r.top-s.top)/scale+35+'px';const label=document.querySelector('.damage-label');label.style.left='75px';label.style.top=(r.top-s.top)/scale+18+'px';label.textContent='目标 01 · 铁甲蟹';const caption=document.querySelector('.damage-caption');caption.style.left='75px';caption.style.top=(r.top-s.top)/scale+76+'px';caption.textContent='目标生命 4 → 2';}if(screen==='zones')showZones()};
const extra=document.createElement('span');extra.className='extra-views';extra.innerHTML='<button data-screen="long">长文</button><button data-screen="cost">惩罚牌</button><button data-screen="zones">区域</button>';document.querySelector('.views').after(extra);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.qty){quantities[b.dataset.qty]=Math.max(0,quantities[b.dataset.qty]+Number(b.dataset.delta));render()}if(b.dataset.filter){document.querySelectorAll('.collection-item').forEach(x=>x.style.display=b.dataset.filter==='all'||x.dataset.kind===b.dataset.filter?'block':'none')}if(b.hasAttribute('data-own-ambush'))notify('己方伏击为空。正式版仅展示引擎允许查看的内容。');if(b.dataset.owner||b.hasAttribute('data-opponent')){let enemy=b.dataset.owner==='enemy'||b.hasAttribute('data-opponent');document.querySelectorAll('[data-owner]').forEach(x=>x.classList.toggle('active',x.dataset.owner===(enemy?'enemy':'own')));document.querySelectorAll('.rail .zone').forEach(x=>{x.dataset.viewer=enemy?'对方':'己方';if(x.dataset.zone==='牌库')x.querySelector('b').textContent=enemy?'47':'46';if(x.dataset.zone==='墓地')x.querySelector('b').textContent=enemy?'3':'4'});}if(b.dataset.zone&&b.dataset.viewer==='对方'){let h=document.querySelector('.drawer h2');if(h)h.textContent='对方 · '+b.dataset.zone;}});
render();
