using System;
using System.Collections.Generic;
using System.IO;

namespace DominionWars.Unity.Runtime
{

/// <summary>
/// Pure path-selection and data-root validation helpers for RuntimeBootstrap.
/// Player builds are intentionally limited to their packaged StreamingAssets
/// copy; repository and working-directory data are editor-only fallbacks.
/// </summary>
public static class RuntimeDataRootPolicy
{
    public const string DataDirectoryName = "data";
    public const string ContentDirectoryName = "content";
    public const string GeneratedMarkerName = ".runtime-data-generated";
    public const string GeneratedMarkerContents =
        "Generated by RuntimeDataStreamingBuildPreprocessor.cs.\n";

    /// <summary>
    /// The resolved path boundary shared by runtime data and presentation
    /// content. Data candidates remain ordered by the existing policy while
    /// content is always the sibling of packaged StreamingAssets/data.
    /// </summary>
    public sealed class RuntimeContentRootSet
    {
        internal RuntimeContentRootSet(
            bool isEditor,
            IEnumerable<string> dataCandidates,
            string streamingAssetsRoot,
            string streamingDataRoot,
            string contentRoot,
            bool requireGeneratedMarker)
        {
            IsEditor = isEditor;
            DataCandidates = new List<string>(dataCandidates ?? Array.Empty<string>()).AsReadOnly();
            StreamingAssetsRoot = streamingAssetsRoot ?? string.Empty;
            StreamingDataRoot = streamingDataRoot ?? string.Empty;
            ContentRoot = contentRoot ?? string.Empty;
            RequireGeneratedMarker = requireGeneratedMarker;
        }

        public bool IsEditor { get; }
        public IReadOnlyList<string> DataCandidates { get; }
        public string StreamingAssetsRoot { get; }
        public string StreamingDataRoot { get; }
        public string ContentRoot { get; }
        public bool RequireGeneratedMarker { get; }
    }

    /// <summary>
    /// Builds the one runtime root set used by RuntimeContentContext. This is
    /// intentionally a pure path seam: it performs no filesystem reads and
    /// therefore can model Player policy in EditMode without changing cwd.
    /// </summary>
    public static RuntimeContentRootSet BuildRuntimeRoots(RuntimeContentEnvironment environment)
    {
        if (environment is null) throw new ArgumentNullException(nameof(environment));

        var streamingAssetsRoot = NonEmpty(environment.StreamingAssetsRoot);
        var streamingDataRoot = CombineDirectory(streamingAssetsRoot, DataDirectoryName);
        var contentRoot = CombineDirectory(streamingAssetsRoot, ContentDirectoryName);
        var candidates = ResolveDataCandidates(
            environment.IsEditor,
            environment.ExplicitDataRoot,
            streamingDataRoot,
            environment.CurrentDirectoryDataRoot,
            environment.ProjectDataRoot,
            environment.RepositoryDataRoot);
        return new RuntimeContentRootSet(
            environment.IsEditor,
            candidates,
            streamingAssetsRoot,
            streamingDataRoot,
            contentRoot,
            requireGeneratedMarker: !environment.IsEditor);
    }

    /// <summary>
    /// Primitive overload for path-policy tests and small hosts that do not
    /// need to construct a RuntimeContentEnvironment first.
    /// </summary>
    public static RuntimeContentRootSet BuildRuntimeRoots(
        bool isEditor,
        string explicitRoot,
        string streamingAssetsRoot,
        string cwd,
        string project,
        string repo)
    {
        return BuildRuntimeRoots(new RuntimeContentEnvironment(
            isEditor,
            explicitRoot,
            streamingAssetsRoot,
            cwd,
            project,
            repo));
    }

    /// <summary>Compatibility vocabulary for hosts that call this a content-root build.</summary>
    public static RuntimeContentRootSet BuildContentRoots(RuntimeContentEnvironment environment)
    {
        return BuildRuntimeRoots(environment);
    }

    /// <summary>
    /// Returns candidate data roots without touching the filesystem. The
    /// arguments are already data-root paths; RuntimeBootstrap supplies
    /// StreamingAssets/data for <paramref name="streaming"/>.
    /// </summary>
    public static string[] ResolveDataCandidates(
        bool isEditor,
        string explicitRoot,
        string streaming,
        string cwd,
        string project,
        string repo)
    {
        if (!isEditor)
            return NonEmptyDistinct(streaming);

        return NonEmptyDistinct(explicitRoot, cwd, project, repo, streaming);
    }

    /// <summary>
    /// Compatibility name for tests and callers that use the earlier policy
    /// vocabulary. It deliberately forwards to the pure resolver above.
    /// </summary>
    public static string[] BuildCandidates(
        string explicitRoot,
        string streaming,
        string cwd,
        string project,
        string repo,
        bool isEditor)
    {
        return ResolveDataCandidates(isEditor, explicitRoot, streaming, cwd, project, repo);
    }

    public static string FindUsableRoot(
        IEnumerable<string> candidates,
        bool requireGeneratedMarker)
    {
        if (candidates is null) return null;

        foreach (var candidate in candidates)
        {
            if (string.IsNullOrWhiteSpace(candidate)) continue;

            try
            {
                var fullPath = Path.GetFullPath(candidate);
                if (IsUsableRoot(fullPath, requireGeneratedMarker))
                    return fullPath;
            }
            catch (ArgumentException)
            {
                // An invalid candidate is not a usable runtime root.
            }
            catch (IOException)
            {
                // An inaccessible candidate is not a usable runtime root.
            }
            catch (UnauthorizedAccessException)
            {
                // An inaccessible candidate is not a usable runtime root.
            }
        }

        return null;
    }

    public static bool IsUsableRoot(string path, bool requireGeneratedMarker)
    {
        if (string.IsNullOrWhiteSpace(path) || !Directory.Exists(path))
            return false;

        try
        {
            if (!Directory.Exists(Path.Combine(path, "cards")) ||
                !Directory.Exists(Path.Combine(path, "decks")))
                return false;

            if (!requireGeneratedMarker) return true;

            var markerPath = Path.Combine(path, GeneratedMarkerName);
            return File.Exists(markerPath) &&
                TextMatches(File.ReadAllText(markerPath), GeneratedMarkerContents);
        }
        catch (ArgumentException)
        {
            return false;
        }
        catch (IOException)
        {
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static string[] NonEmptyDistinct(params string[] values)
    {
        var result = new List<string>(values.Length);
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var value in values)
        {
            if (!string.IsNullOrWhiteSpace(value) && seen.Add(value))
                result.Add(value);
        }

        return result.ToArray();
    }

    private static string NonEmpty(string value)
    {
        return string.IsNullOrWhiteSpace(value) ? string.Empty : value;
    }

    private static string CombineDirectory(string parent, string child)
    {
        if (string.IsNullOrWhiteSpace(parent)) return string.Empty;
        try
        {
            return Path.Combine(parent, child);
        }
        catch (ArgumentException)
        {
            return string.Empty;
        }
        catch (NotSupportedException)
        {
            return string.Empty;
        }
    }

    private static bool TextMatches(string actual, string expected)
    {
        return string.Equals(
            actual.Replace("\r\n", "\n").Trim(),
            expected.Replace("\r\n", "\n").Trim(),
            StringComparison.Ordinal);
    }
}
}
