<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>DominionWars.Data</AssemblyName>
    <RootNamespace>DominionWars.Data</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engine\DominionWars.Engine.csproj" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
